version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/js/apps/admin-ui"
      - "/js/libs/*"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directories:
      - "/js/apps/admin-ui"
      - "/js/libs/*"
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.keycloak:*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]